### PR TITLE
Adding extent reports for .NET

### PR DESCRIPTION
**Pull request by karthikbhatnagar**

### CODE REVIEW

**Comment by polusok** [comment]
please add link for your modification

**Comment by karthikbhatnagar** [comment]
hi Mykhailo,

please let me know if this pull request looks good or we can close it so I will send in a new one if that's easy for you.  Thank you!

**Comment by polusok** [comment]
Please correct formatting as per contribution rules https://github.com/atinfo/awesome-test-automation/blob/master/CONTRIBUTING.md

`* [project-name](http://example.com/) - A short description ends with a dot.`

**Comment by karthikbhatnagar** [comment]
Thanks, i craeted new commit.

**Pull request merged**
