### PR TITLE
Added Differencify

### PR DESCRIPTION
**Pull request by NimaSoroush**
Added [Differencify](https://github.com/NimaSoroush/differencify) - A library for visual regression testing

### CODE REVIEW

**Comment by polusok** [comment]
could you please move it to "useful lib" category

**Comment by NimaSoroush** [comment]
@polusok : This library is for Web UI testing, just like Gemini in this list

**Comment by polusok** [comment]
i think we need sub-list like in python list https://github.com/atinfo/awesome-test-automation/blob/master/python-test-automation.md#web-ui-test-automation

**Comment by NimaSoroush** [comment]
Javascript has the same sub-list, right? Am I missing something here!
https://github.com/atinfo/awesome-test-automation/blob/master/javascript-test-automation.md#web-ui-test-automation

**Comment by NimaSoroush** [comment]
@polusok : Any update on this?

**Pull request merged**
