### PR TITLE
Added Awesome Robot Framework List

### PR DESCRIPTION
**Pull request by Tset-Noitamotua**
Added Awesome Robot Framework list as `generic test automation`

### CODE REVIEW

**Comment by polusok** [comment]
Please add it only to python and java list after robotframework item (not at the end) as it's related only to python and java tools

**Comment by Tset-Noitamotua** [comment]
It is not related to Python and Java tools only ... it is generic, thus regarding SUTs it's lanuage agnostic. Also it's remote library interface enables it to be used with almost any other tool / language (SAP / ABAP / C# / C++ ... just to name a few).

It is written in Python is released through pip and as a standalone .jar bundling Jython, yes - but it is not limited to test software which is written in Python or Java.

May be then it is better to add a completly new section for generic frameworks, where RF would fit better than under Python or Java.

Also I have not seen a model based testing section which is kind of also related to test automation.

Cheers
Test

**Comment by polusok** [comment]
I know RF eco system, and mostly RF used for python or java, that's why i think it should be there.
I would gladly add new generic frameworks but however how many generic frameworks do you know more? 

Regarding model based testing, make a pull request and add tools.

**Comment by Tset-Noitamotua** [comment]
I don't know other generic test automation frameworks, either. I guess there is no other, or at least no good one else I and you would know :smile:   That's what makes RF so special :rofl:

**Comment by polusok** [comment]
I know a few other however I don't see a reason to create such list for a few small amount of tools. So please add it to java and python. Also it may be a good option to move RF to list to our repository for support as we have bigger involvement.

**Comment by Tset-Noitamotua** [comment]
Oh ... what other frameworks are there? Please share.

So in [python-test-automation.md][1] I would add like this?
image


[1]: https://github.com/atinfo/awesome-test-automation/blob/master/python-test-automation.md

**Comment by polusok** [comment]
Yes, that's correct place 

http://staf.sourceforge.net/
http://citrusframework.org/
etc ..

**Comment by Tset-Noitamotua** [comment]
I remember to have bookmarked STAF when I started researching about test automation  ... but never tried it. 

Never heard of cirtursfr. Regarding it's description it does not seem to be really generic - seems to be good especially for "Automated integration tests for message protocols"

**Pull request closed without merging**
