### PR TITLE
SWTBot

### PR DESCRIPTION
**Pull request by dannybarrientos**
SWTBot is an open-source Java based UI/functional testing tool for testing SWT, Eclipse and GEF based applications.

SWTBot provides APIs that are simple to read and write. The APIs also hide the complexities involved with SWT and Eclipse. This makes it suitable for UI/functional testing by everyone, not just developers. SWTBot also provides its own set of assertions that are useful for SWT. You can also use your own assertion framework with SWTBot.

### CODE REVIEW

**Comment by polusok** [comment]
please make it one line description without line breaks in list

**Comment by dannybarrientos** [comment]
SWTBot es una herramienta de pruebas de interfaz de usuario funcional basada en Java de código abierto para probar aplicaciones basadas en SWT, Eclipse y GEF

**Comment by dannybarrientos** [comment]
SWTBot is an open-source Java based UI/functional testing tool for testing SWT, Eclipse and GEF based applications.

**Comment by polusok** [comment]
Nice, please make a change to pull request

**Pull request closed without merging**
