### PR TITLE
Add js-testrunners-bench

### PR DESCRIPTION
**Pull request by vitalets**
I suggest to add **Benchmarks** sub-section for test-runners comparison tools and resources.

Thanks in advance!

### CODE REVIEW

**Comment by polusok** [comment]
please move it to Resources section.

**Comment by vitalets** [comment]
Hi @polusok ! 
It's already inside **Resources** section as sub-section:
* Resources
  * Websites
  * Benchmarks

Or do you mean another structure?

**Comment by polusok** [comment]
True sorry mixed things

**Comment by vitalets** [comment]
Never mind! :)
Thanks for managing this list!

**Pull request merged**
